name: network
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  dio: ^5.7.0
  equatable: ^2.0.7
  pretty_dio_logger: 1.3.1
  freezed_annotation: 2.4.4
  freezed: ^2.5.7
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  
dev_dependencies:
  build_runner: 2.4.10
  flutter_test:
    sdk: flutter
  json_serializable: 6.8.0
  very_good_analysis: 5.1.0
  injectable_generator: 2.6.2
flutter: